name: Build Linux Executable Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-lin-executable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup ARES Environment
        uses: ./.github/workflow-actions/setup-ares

      - name: Build executable
        run: |
          make build-executable

      - name: Verify executable
        run: |
          ./dist/ares --version

      - name: Build simulation units
        run: |
          make -C examples/sim_unit all

      - name: Run all workflow examples with Executable
        run: |
          make -C examples ARES=../dist/ares

      - name: Cleanup ARES Environment
        uses: ./.github/workflow-actions/cleanup-ares
